const quotes = [
  "Breathe. This moment matters.",
  "You are exactly where you need to be.",
  "Slow down. You're doing fine.",
  "Peace begins with a single breath.",
  "Nothing is urgent right now.",
  "Let go of what you cannot control.",
  "Be here now.",
  "The present moment is a gift.",
  "Allow yourself to simply be.",
  "Your breath is your anchor.",
  "Calm mind brings inner strength.",
  "Inhale peace, exhale stress.",
  "Every breath is a new beginning.",
  "Softness is strength.",
  "Notice without judgment.",
  "Return to your center.",
  "Stillness holds all answers.",
  "Listen to the silence between breaths.",
  "You are enough, just as you are.",
  "Let thoughts pass like clouds.",
  "Root yourself in this moment.",
  "Gentleness with yourself is healing.",
  "The body breathes itself. Allow it.",
  "Pause and reconnect.",
  "Mindfulness is the path to peace.",
  "Everything you need is within you.",
  "Accept what is. Allow what will be.",
  "This too shall pass.",
  "Find joy in the ordinary.",
  "Release tension with every exhale.",
  "Be kind to your wandering mind.",
  "Each inhale brings clarity.",
  "Each exhale releases worry.",
  "Wherever you are, be all there.",
  "Your presence is powerful.",
  "Rest in awareness.",
  "Breathe deeply, live fully.",
  "Simplicity brings peace.",
  "Let your breath guide you home.",
  "The universe is within you.",
  "Quiet mind, open heart.",
  "Peace is this moment without judgment.",
  "You are safe in this moment.",
  "Feel the life in your breath.",
  "Stillness speaks louder than thoughts.",
  "Beneath thoughts, there is calm.",
  "You are not your thoughts.",
  "Let go of doing, embrace being.",
  "Mindfulness is love in action.",
  "The breath is a bridge to presence.",
  "Allow space between stimulus and response.",
  "Compassion starts with yourself.",
  "The only moment is now.",
  "Breathe in courage, breathe out fear.",
  "Gratitude turns what we have into enough.",
  "In stillness, find wisdom.",
  "Your breath is always with you.",
  "Let today be enough.",
  "Nature does not hurry, yet everything is accomplished.",
  "Presence is the greatest present.",
  "When you breathe, you are truly alive.",
  "Mindfulness is remembering to come back.",
  "The quieter you become, the more you can hear.",
  "Peace comes from within.",
  "Every moment is a fresh beginning.",
  "Breathe in light, breathe out darkness.",
  "You are the sky; thoughts are just clouds.",
  "Rest your mind in the breath.",
  "Mindfulness is the art of being awake.",
  "Let your breath be your sanctuary.",
  "The present is where life happens.",
  "Be gentle with this moment.",
  "Breathe in gratitude, breathe out negativity.",
  "Stillness is the language of the soul.",
  "You don't need to be perfect, just present.",
  "Each breath connects you to life.",
  "Pause and feel your aliveness.",
  "Mindfulness is the key to everything.",
  "Breathe and let go.",
  "The breath is a constant companion.",
  "Find peace in the pause.",
  "Your presence heals.",
  "Mindfulness is noticing what's already here.",
  "Breathe deeply, think clearly.",
  "The moment is complete as it is.",
  "Let your breath soften your edges.",
  "Return to the simplicity of breathing.",
  "Mindfulness is paying attention on purpose.",
  "Breathe in calm, breathe out chaos.",
  "The breath knows the rhythm of life.",
  "Presence is your superpower.",
  "Rest in the rhythm of your breath.",
  "Mindfulness transforms ordinary into extraordinary.",
  "Breathe into your heart space.",
  "Everything is clearer when you're present.",
  "The breath is the whisper of the soul.",
  "Mindfulness is coming home to yourself.",
  "Breathe and remember who you are.",
  "This moment holds infinite possibilities.",
  "Presence is the antidote to anxiety.",
  "Breathe like every breath matters.",
  "Mindfulness is the art of living deeply.",
  "Your breath is your home.",
  "Be still and know.",
  "Breathe in possibility, breathe out limitation.",
  "The present moment is your true home.",
  "Mindfulness is the space between thoughts.",
  "Let your breath be your meditation.",
  "Presence is the foundation of peace.",
  "Breathe and trust the process."
];

const quoteEl = document.getElementById("quote");
const instruction = document.getElementById("instruction");
const skipBtn = document.getElementById("skip");

quoteEl.textContent = quotes[Math.floor(Math.random() * quotes.length)];

let inhale = true;

setInterval(() => {
  instruction.textContent = inhale ? "Exhale..." : "Inhale...";
  inhale = !inhale;
}, 3000);

skipBtn.addEventListener("click", () => {
  window.location.href = "https://www.google.com";
});
